server:
  port: 9090

spring:
  application:
    name: gateway-zuul
  profiles:
    active: dev
  config:
    import: optional:configserver:https://localhost:8888

  #Config Server
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: config-server

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

#Zuul Routing
zuul:
  routes:
    productUser: #routing id
      path: /productUser/** #zuul context root
      serviceId: product-user #spring application name

    productCatalog:
      path: /productCatalog/**
      serviceId: product-catalog

    productOrder:
      path: /productOrder/**
      serviceId: product-order
