server:
  port: 8000

signing:
  key: jwtkey #사용할 서명키

#Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # 인스턴스를 구별하기 위한 설정

spring:
  application:
    name: gateway-zuul
  profiles:
    active: dev
  config:
    import: optional:configserver:https://localhost:8888

  #Config Server
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: config-server

#Zuul Routing
zuul:
  routes:
    product-user: #routing id
      path: /product-user/** #zuul context root
      serviceId: product-user #spring application name

    product-catalog:
      path: /product-catalog/**
      serviceId: product-catalog

    product-order:
      path: /product-order/**
      serviceId: product-order


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus